name: test

defaults:
  run:
    shell: bash

env:
  TERM: xterm-256color

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.3
        with:
          submodules: true
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: run dockerized test
        uses: docker/build-push-action@v5.3.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          outputs: type=local,dest=/tmp/output/
          target: ci
      - name: print dockerized test output
        run: scripts/cat-all.sh /tmp/output/ --github
